In [1]:
#np.array
import numpy as np
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [12]:
#2D and 3D array
#import numpy as np
b = np.array([[1,2,3],[4,5,6]])
print(b)
b.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [8]:
#dtype
np.array([1,2,3,4],dtype = float)


array([1., 2., 3., 4.])

In [10]:
#np.arange
np.arange(1,15,2)

array([ 1,  3,  5,  7,  9, 11, 13])

In [11]:
#np.reshape
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [13]:
#np.ones
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
#np.zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
#np.random
np.random.random((3,4))

array([[0.08056219, 0.93519094, 0.37583163, 0.95655739],
       [0.50485074, 0.19898968, 0.72468907, 0.16524345],
       [0.54645503, 0.34400244, 0.89557389, 0.32311641]])

In [21]:
#np.linspace
np.linspace(-10,10,5,dtype = int)

array([-10,  -5,   0,   5,  10])

In [19]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
#ARRAY ATTRIBUTES
a1 = np.arange(10,dtype=np.int32).reshape(1,10).reshape(3,4)

a1

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [37]:
a2 =  np.arange(12,dtype=float)
a2
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [30]:
#ndim tell about dim
a3.ndim

2

In [38]:
#shape 
print(a3.shape)

(2, 2, 2)


In [39]:
#size
print(a2.size)

12


In [40]:
#itemsize
a2.size

12

In [41]:
#dtypes
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


In [43]:
#CHANGING DATAYPE
#astype
a3.astype(np.int64)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int64)

In [44]:
a1 = np.arange(12).reshape(3,4)
a1


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
a2 = np.arange(12,24).reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [46]:
#SCALAR OPERATION
#arithmetic
a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [47]:
#relational
a2==15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [48]:
#VECTOR OPERATION
#arithmetic
a1**a2

array([[          0,           1,       16384,    14348907],
       [          0, -1564725563,  1159987200,   442181591],
       [          0,  1914644777, -1304428544,  -122979837]])

In [49]:
#ARRAY FUNCTION
a1 = np.random.random((3,3))
a1

array([[0.14549409, 0.11215177, 0.7990747 ],
       [0.20997767, 0.94178538, 0.83978234],
       [0.84786502, 0.75037574, 0.49694478]])

In [50]:
#max/mean/sum/prod
# 0 -> col and 1->row
np.prod(a1,axis=0)

array([0.02590271, 0.07925686, 0.33347421])

In [51]:
#mean/median/std/var
np.var(a1,axis=1)

array([0.10001583, 0.10473345, 0.02187516])

In [52]:
#trignometric functions
np.sin(a1)

array([[0.14498131, 0.11191681, 0.71671112],
       [0.20843806, 0.80860981, 0.74449782],
       [0.74986964, 0.68191364, 0.4767421 ]])

In [59]:
#dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
np.dot(a2,a3)


array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [55]:
#log and exponents
np.exp(a1)

array([[1.1566109 , 1.11868263, 2.22348259],
       [1.23365051, 2.56455604, 2.31586285],
       [2.33465707, 2.11779561, 1.64369175]])

In [57]:
#round/floor/ceil
np.ceil(np.random.random((2,3))*100)

array([[74.,  8., 93.],
       [22., 29., 80.]])

In [60]:
#INDEXING SLICING
a1

array([[0.14549409, 0.11215177, 0.7990747 ],
       [0.20997767, 0.94178538, 0.83978234],
       [0.84786502, 0.75037574, 0.49694478]])

In [61]:
a2[1,0]

4

In [63]:
a1[2:5:2]

array([[0.84786502, 0.75037574, 0.49694478]])

In [64]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [65]:
a2[2:]

array([[ 8,  9, 10, 11]])

In [66]:
a3[:4]

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [67]:
a3[::4]

array([[12, 13, 14]])

In [68]:
#iterating
for i in a1:
    print(i)

[0.14549409 0.11215177 0.7990747 ]
[0.20997767 0.94178538 0.83978234]
[0.84786502 0.75037574 0.49694478]


In [69]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [71]:
for i in np.nditer(a3):
    print(i)

12
13
14
15
16
17
18
19
20
21
22
23


a3>ravel(

In [72]:
a3.ravel()

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])